node {
    if(env.BRANCH_NAME == 'main'){
        stage('Build Main') {
            echo 'Building main'
        }
    }

    if(env.BRANCH_NAME == 'dev'){
        stage('Build Dev') {
            echo 'Building dev'
        }
    }
}
