pipeline {
    agent any
    options {
        checkoutToSubdirectory('someSubDir')
    }
    stages {
        stage('Build') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
